// Personal data
const siteData = {
  name: "Gianfranco Di Pisa Echague",
  role: "Técnico en Electrónica · Fullstack Jr. · Seguridad Electrónica",
  contact: {
    email: "giandatas@hotmail.com",
    phone: "+54 9 280 4856318",
    location: "Puerto Madryn, Chubut, Argentina",
  },
  skills: [
    "Electrónica y micro soldadura",
    "Reparación de dispositivos",
    "CCTV / Seguridad electrónica",
    "Redes informáticas (Cisco)",
    "Ciberseguridad / Pentesting",
    "Robótica y automatización",
    "Impresión 3D FDM",
    "Energía solar renovable",
    "Python / Django / PostgreSQL",
    "HTML / CSS / Bootstrap / Vue.js",
    "Diseño y armado de redes",
  ],
  experience: [
    {
      company: "Brava Smart",
      location: "Balneário Camboriú, Santa Catarina, Brasil",
      role: "Técnico Especializado en Reparación y Mantenimiento",
      dates: "Mayo 2024 – Diciembre 2024",
      bullets: [
        "Diagnóstico preciso de placas y documentación de problemas técnicos.",
        "Gestión y presupuestos a clientes mediante WhatsApp Business.",
        "Instalación de hardware y configuración de software avanzado en computadores y portátiles.",
        "Reparación electrónica con micro soldadura de dispositivos Android/iPhone, reemplazo de piezas usando diagramas esquemáticos.",
      ],
    },
    {
      company: "Souzza Servicios Eléctricos",
      location: "Balneário Camboriú, Santa Catarina, Brasil",
      role: "Asistente electricista en obra",
      dates: "Enero 2024 – Abril 2024",
      bullets: [
        "Instalación de canalizaciones eléctricas en muros con herramientas manuales según planos técnicos.",
        "Colaboración en tendido de cables y montaje de cajas, cumpliendo normas NR-10.",
        "Tareas en altura con EPI certificado en obras residenciales.",
        "Limpieza y mantenimiento del área de trabajo siguiendo normas locales.",
        "Fortalecimiento de habilidades de comunicación en un entorno internacional.",
      ],
    },
    {
      company: "Segelec Alarmas Seguridad Electrónica",
      location: "Puerto Madryn, Chubut, Argentina",
      role: "Operador de Monitoreo y asistencia técnica",
      dates: "Septiembre 2022 – Septiembre 2023",
      bullets: [
        "Atención de eventos de emergencia con comunicación efectiva entre las partes.",
        "Planificación y ejecución de protocolos de incidencia.",
        "Control y resguardo de datos sensibles bajo las directivas empresariales.",
        "Documentación detallada de cada asistencia del área técnica.",
        "Conocimientos avanzados y específicos de Seguridad Electrónica.",
      ],
      ref: { name: "Hernán Pereyra", phone: "280 4182912" },
    },
    {
      company: "Desarrollador de Prototipos",
      location: "Smartlab · Puerto Madryn, Argentina",
      role: "Desarrollador de Prototipos",
      dates: "Enero 2022 - Diciembre 2022",
      bullets: [
        "Aplicación de las etapas del proceso tecnológico.",
        "Desarrollo de programas de control.",
        "Diseño y construcción de PCB.",
        "Uso básico de software de diseño gráfico.",
      ],
      ref: { name: "German Blum", phone: "280 4638866" },
    },
    {
      company: "Gicanet (Autónomo)",
      location: "Puerto Madryn / Remoto",
      role: "Soporte técnico en Informática",
      dates: "Diciembre 2019 - Actualidad",
      bullets: [
        "Armado, mantenimiento y reparación de PCs.",
        "Asesoría y presupuestos a clientes.",
        "Análisis y optimización de sistemas operativos (Windows, Linux).",
      ],
    },
  ],
  education: [
    {
      institution: "ESETP N°703 “Jose Toschke”",
      location: "Puerto Madryn, Chubut, Argentina",
      title: "Técnico en Electrónica (Grado Medio)",
      dates: "Promoción Diciembre 2019",
      notes: "Promedio analítico: 8 · Talleres de robótica y automatización · Diseño e Impresión 3D FDM · Medallas en la Liga Nacional de Robótica ed. 2018-2019 · Proyecto tecnológico inclusivo Tecnópolis ed. 2016.",
    },
    {
      institution: "INET - Centro de Formación Profesional N°651",
      location: "Puerto Madryn, Chubut, Argentina",
      title: "Instalador de Redes Informáticas (curso certificación Cisco)",
      dates: "Marzo 2021 – Julio 2021",
      notes: "Configuración de router, switch y seguridad básica · Cableado y fibra · Solución de problemas de red · Planificación hogareña o pequeña empresa · Soporte técnico.",
    },
    {
      institution: "INET - Centro de Formación Profesional N°651",
      location: "Puerto Madryn, Chubut, Argentina",
      title: "Asistente en Ciberseguridad (curso certificación Cisco)",
      dates: "Julio 2021 – Diciembre 2021",
      notes: "Etapas del Pentesting · Prevención de tácticas de ciberdelincuentes · Laboratorios en Linux (ParrotOS + BurpSuite): Phishing, Brute Force, RFI, LFI, XSS, SQL Injection.",
    },
    {
      institution: "INET - Centro de Formación Profesional N°651",
      location: "Puerto Madryn, Chubut, Argentina",
      title: "Programador Fullstack Jr. (curso certificación INET - 364 horas)",
      dates: "Marzo 2022 – Diciembre 2022",
      notes: "Lógica y arquitectura de datos · Python y POO · HTML y CSS · Bootstrap · Vue.js · Django · PostgreSQL · Creación de API Rest · Proyecto integrador: CRUD + Sistema de gestión administrativa escolar.",
    },
    {
      institution: "INET - Centro de Formación Profesional N°651",
      location: "Puerto Madryn, Chubut, Argentina",
      title: "Instalador de Sistemas de Energía Renovable (curso certificación INET)",
      dates: "Marzo 2023 – Julio 2023",
      notes: "Variables técnico-ambientales de la energía solar · Presupuesto y cálculos · Práctica real con kit solar 6kW Growatt.",
    },
    {
      institution: "INET - Centro de Formación Profesional N°651",
      location: "Puerto Madryn, Chubut, Argentina",
      title: "Instalador de Sistemas CCTV con monitoreo (curso certificación INET - 125 horas)",
      dates: "Mayo 2025 – Julio 2025",
      notes: "Leyes e implicaciones de sistemas CCTV · Configuración DVR/NVR (Dahua & Hikvision) · Planificación de instalaciones · Tipos de cámaras · Práctica real en campo (100m²).",
    },
    {
      institution: "ESETP N°703 “Jose Toschke”",
      location: "Puerto Madryn, Chubut, Argentina",
      title: "Cursos: Software y diseño de robots con Arduino",
      dates: "2017",
      notes: "Robótica y programación de microcontroladores.",
    },
    {
      institution: "ESETP N°703 “Jose Toschke”",
      location: "Puerto Madryn, Chubut, Argentina",
      title: "Cursos: Mantenimiento y operación de impresoras 3D",
      dates: "2018",
      notes: "Operación y mantenimiento de impresoras 3D FDM.",
    },
    {
      institution: "Universidad Tecnológica Nacional FRC",
      location: "Córdoba, Argentina",
      title: "Ingeniería en Sistemas de la Información (incompleto)",
      dates: "Marzo 2021 – Diciembre 2021",
      notes: "Cursada parcial de la carrera.",
    },
    {
      institution: "Centro de Formación Profesional N°651",
      location: "Puerto Madryn, Chubut, Argentina",
      title: "Curso: Automatización Digital",
      dates: "Marzo 2023 – Mayo 2023",
      notes: "Automatismos varios con programación y electrónica aplicada.",
    },
  ],
  experiences: [],
  blog: [],

  services: [
    {
      icon: "📱",
      name: "Reparación de dispositivos móviles",
      desc: "Micro soldadura, cambio de pantallas, baterías, conectores y componentes. Android e iPhone.",
      price: "desde $25.000",
      place: "Taller / a domicilio",
    },
    {
      icon: "📺",
      name: "Reparación de TV y electrodomésticos",
      desc: "Televisores, hornos, lavadoras, pavas y electrodomésticos pequeños. Diagnóstico con instrumental.",
      price: "desde $18.000",
      place: "Taller / a domicilio",
    },
    {
      icon: "💻",
      name: "Servicio técnico de PC",
      desc: "Armado, upgrade, mantenimiento preventivo, reparación, análisis y optimización de Windows y Linux.",
      price: "desde $15.000",
      place: "Taller / a domicilio",
    },
    {
      icon: "🎮",
      name: "Consolas PlayStation y Xbox",
      desc: "Limpieza interna, cambio de pasta térmica, reparación y mantenimiento. PS4, PS5, Xbox One y Series.",
      price: "desde $22.000",
      place: "Taller",
    },
    {
      icon: "📹",
      name: "Sistemas de CCTV y seguridad",
      desc: "Cámaras, DVR/NVR, instalación, configuración y monitoreo. Dahua, Hikvision y compatibles.",
      price: "consultar",
      place: "A domicilio",
    },
    {
      icon: "🖨️",
      name: "Mantenimiento de impresoras 3D",
      desc: "Limpieza, calibración, cambio de boquillas, corrección de nivelación y mejora de calidad de impresión.",
      price: "desde $12.000",
      place: "Taller / a domicilio",
    },
    {
      icon: "🔌",
      name: "Instalaciones eléctricas",
      desc: "Canalizaciones, tableros, tendido de cables y puesta en marcha, según normas.",
      price: "consultar",
      place: "A domicilio",
    },
    {
      icon: "☀️",
      name: "Energía solar",
      desc: "Estudio, presupuesto e instalación de sistemas solares para casa o pyme.",
      price: "consultar",
      place: "A domicilio",
    },
  ],

  serviceClient: {
    title: "Para quién trabajo",
    text: "Clientes sabíos que saben valorar el trabajo de un buen profesional. No busco el más barato: busco al que le importa que el trabajo quede bien hecho y dure.",
  },

  serviceWhere: {
    title: "Dónde trabajo",
    text: "Desde mi taller en Puerto Madryn, y también a domicilio cuando hace falta, con un servicio personalizado y atención directa. Sin intermediarios: hablás con quien hace el trabajo.",
  },
};
